theme: jekyll-theme-minimal 
title: [Daniel Nimmervoll]
description: [exploring and creating with passion and people ...]
logo: [portrait.jpg]
show_downloads: ["false"]
#google_analytics: [Your Google Analytics tracking ID]
